version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?provide POSTGRES_PASSWORD env}
      DB_USER: shortener
      DB_PASSWORD: ${DB_PASSWORD?provide DB_PASSWORD env}
      DB_NAME: gourl_shortener_db
    ports:
      - "5433:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username shortener --dbname gourl_shortener_db",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./server/scripts/:/docker-entrypoint-initdb.d/

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  go-app:
    build:
      context: server
    container_name: gourl_shortener_server
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      GOURLAPP_storage_dbConnString: postgres://shortener:foo_bar@postgres:5432/gourl_shortener_db?sslmode=disable
      GOURLAPP_storage_type: postgres
      GOURLAPP_cache_host: redis
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8080/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  ui-app:
    build:
      context: client
      args:
        - BACKEND_URL=${BACKEND_URL:-http://localhost:8082}
    container_name: gourl_shortener_client
    depends_on:
      go-app:
        condition: service_healthy
    ports:
      - "3000:80"
