server:
  host: 0.0.0.0
  port: 8080
storage:
  type: postgres
  dbConnString: "user=shortener password=<pass> dbname=gourl_shortener_db sslmode=disable"
cache:
  enabled: true
  host: localhost
  port: 6379
  database: 0
shortenerProps:
  length: 6
  maxAttempt: 5
