server:
  host: localhost
  port: 8080
db_conn_string: "user=postgres password=foo_bar dbname=gourl_shortener sslmode=disable"
cache:
  host: localhost
  port: 6379
  database: 0
  username: <user>
  password: <pass>
