server:
  host: localhost
  port: 8080
storage:
  type: in-memory
  # only applicable for other database options other than in-memory
  # db_conn_string: "user=postgres password=<pass> dbname=gourl_shortener sslmode=disable"
cache:
  enabled: false
  # only valid for redis options
  # host: localhost
  # port: 6379
  # database: 0
  # username: <user>
  # password: <pass>
shortener_props:
  length: 6
  max_attempt: 5
