server:
  host: 0.0.0.0
  port: 8080
storage:
  type: postgres
  db_conn_string: "user=postgres dbname=gourl_shortener sslmode=disable"
cache:
  enabled: true
  host: localhost
  port: 6379
  database: 0
shortener_props:
  length: 6
  max_attempt: 5
